name: Validate and Merge
on:
  pull_request:
    branches:
    - master
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Kubernetes Manifests
        uses: andloh/actions-k8s-manifests-validate-kubeval@v1.0.6
        with:
          files: .
          token: ${{ secrets.GITHUB_TOKEN }}
          openshift: true
          comment: true
          ignored_filename_patterns: gha.yaml
  autoapprove:
    needs: [validation]
    if: ${{ github.actor.name == 'andloh' }}
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      name: autoapprove
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
