name: Lint, approve and merge
on:
  pull_request:
    branches:
    - master
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with: 
        config_file: ../.yamllint-config.yaml
  autoapprove:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      name: autoapprove
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
